DSP3-apps/ncea-frontend

__tests__/services/handlers/searchApi.spec.ts, src/services/handlers/mocks/more-info-response.ts, src/services/handlers/searchApi.ts
This mocks out the network request for the "More Info" document details, so the VPN connection is not required, and returns a single mock document instead.
=> Mock out "More Info" network request

__tests__/config/environmentConfig.spec.ts, __tests__/controllers/web/HomeController.spec.ts, __tests__/infrastructure/plugins/views.spec.ts, __tests__/routes/web/__snapshots__/404.spec.ts.snap, __tests__/routes/web/__snapshots__/accessibility.spec.ts.snap, __tests__/routes/web/__snapshots__/dateSearch.spec.ts.snap, __tests__/routes/web/__snapshots__/detailsPage.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchGet.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchPost.spec.ts.snap, __tests__/routes/web/__snapshots__/home.spec.ts.snap, __tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, __tests__/schema/environmentConfig.schema.spec.ts, src/config/environmentConfig.ts, src/controllers/web/HomeController.ts, src/infrastructure/plugins/auth.ts, src/infrastructure/plugins/views.ts, src/interfaces/environmentConfig.interface.ts, src/routes/web/home.ts, src/schema/environmentConfig.schema.ts, src/utils/constants.ts, src/views/layout/default.njk
This PR implements a logout system on our side, so AGM do not need to modify the logout system in DSP.
A new `/logout` endpoint has bee added and the logout button makes a `GET` request to this, including a `redirect_uri` query parameter which will redirect the user back to the page they logged out from. It removes the cookie from the browser so they appear logged out.
The value of `redirect_uri` is validated against allowed hostnames for security, although less necessary for logging out.
The tests that broke due to the changes have also been updated.
=> Implement logout system

__tests__/routes/web/__snapshots__/accessibility.spec.ts.snap, __tests__/routes/web/__snapshots__/detailsPage.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchPost.spec.ts.snap, __tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, __tests__/services/handlers/searchApi.spec.ts, public/scripts/badges.js, public/scripts/filters.js, public/scripts/keywordsFilter.js, src/assets/sass/templates/_results.scss, src/utils/constants.ts, src/utils/processFilterRSortOptions.ts, src/utils/searchFilters.ts, src/views/macros/icons/cross.njk, src/views/macros/icons/icon.njk, src/views/partials/results/badges.njk, src/views/partials/results/filters.njk, src/views/partials/results/summary.njk, src/views/screens/results/template.njk
In the DSP core platform, when a filter is applied a badge is shown above the search results indicating what filters are currently active. These badges can be clicked on, which, if done, will disable the respective filter and remove the badge.
I have implemented this badge system. The difference between this and DSP is that the badges only show once the filters have been applied, which was the desired behaviour over DSP where they show up the moment a filter is selected.
If you click on one of the badges, it will reset the filter that corresponds to the badge, but you must apply the filters again to have the results changed.
The badges have the same styling as the DSP equivalents.
Modify any number of filters, then apply. The page should reload and badges should show up for all applied …
=> Implement filter badges

public/scripts/dataModal.js, public/scripts/keywordsFilter.js, public/scripts/location.js, src/assets/sass/templates/_results.scss, src/views/partials/results/filters.njk
- This PR will add the keywords filter functionality under Map section
- [NCEA-176 - Fix keyword input](https://dsp-support.atlassian.net/browse/NCEA-176)
- Also added one functionality related to duplicate keyword selection. If a user selects the A keyword and then again selects the same keyword, at this point the A keyword won't be appended to the badge component
- [Search results](http://localhost:3000/natural-capital-ecosystem-assessment/search?scope=ncea&date-before=&date-after=&licence=&keywords=Another+free+word+test%2C21+day+performance&q=AE0101&rpp=20&srt=most_relevant&jry=qs&pg=1)
=> NCEA-176 Fix keyword input

public/scripts/dataModal.js, public/scripts/filters.js, public/scripts/location.js, src/views/partials/results/sidebar.njk
In the code PR, I have added the Apply Filter and Clear Filter buttons on the map view section. Now the map view section, will also behaves like same as search result filters. When a user selects the filter items present on the map view section, and then clicks on the Apply filters, then it will call invokeMapResults(true) function will all the applied form filters. If user clicks on clearFilters, then it will clear all the filters and call invokeMapResults().
- [NCEA-187 - Add clear/apply filters back to map](https://dsp-support.atlassian.net/browse/NCEA-187)
Also added a scenarios, when a user selects any filters on the search result page without clicking the Apply Filters. If user clicks on the map view, then all the filters will also get applied on the map results filter sections.
- …
=> NCEA-187 Add clear/apply filters back to map

__tests__/routes/web/__snapshots__/accessibility.spec.ts.snap, __tests__/routes/web/__snapshots__/detailsPage.spec.ts.snap, __tests__/routes/web/__snapshots__/feeds.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchPost.spec.ts.snap, __tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, __tests__/routes/web/feeds.spec.ts, src/utils/constants.ts
- I have updated the atom feed urls which will gives only the feeds related to NCEA.
Updated URLS:
1.  https://naturalengland.blog.gov.uk/tag/ncea/feed/
2. https://defraenvironment.blog.gov.uk/category/research-and-data-analysis/ncea-programme/feed/
Issued Id: NCEA-211.
- ...
=> feat(frontend): Filter Atom feeds to just NCEA related.

src/utils/formatSearchResponse.ts
when we search using keywords and license filters, if there is no record exist, then API is getting failed. So in branch, that issue is fixed
- [NCEA-220 - Fix Keyboard and License Filters API issue ](https://dsp-support.atlassian.net/browse/NCEA-220)
- [Search Result](http://localhost:3000/natural-capital-ecosystem-assessment/search?date-before=&date-after=&licence=&keywords=&scope=ncea&q=asdasd&rpp=20&srt=most_relevant&jry=qs&pg=1)
=> feat(frontend): fix the keywords and license filters issue

__tests__/routes/web/__snapshots__/404.spec.ts.snap, __tests__/routes/web/__snapshots__/accessibility.spec.ts.snap, __tests__/routes/web/__snapshots__/dateSearch.spec.ts.snap, __tests__/routes/web/__snapshots__/detailsPage.spec.ts.snap, __tests__/routes/web/__snapshots__/feeds.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchGet.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchPost.spec.ts.snap, __tests__/routes/web/__snapshots__/home.spec.ts.snap, __tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, src/utils/processFilterRSortOptions.ts, src/utils/queryStringHelper.ts
Issue: There is a function called "readQueryParams" from this we are reading the filter values and passed it to the result API, this "readQueryParams"
function will return the query string with comma separated. when it comes to organisation or Data format, in which  some filter items which contain in name it self a comma character is there, hence it treated as a separate filter value when it doing the query string split by comma. this comma separated values contains some other  name which are not expected values.
Fix: I tried to modify "readQueryParams"  function it will return the array of filter items when key value  is available, but it is used in so many places in the source code, for avoiding complexity and more clarity, I created the new function  called " readListQueryParams ", it …
=> fix(elements): Filtering for all on org or Data Format is unchecking some checkboxes

public/scripts/location.js
The bounding boxes seemed to always show for every single results on the map, even if you had filtered the results. From investigating, this seemed to be caused because they array that holds the bounding boxes was never cleared from the first search, every time you filtered your results it would just extend the bounding box array, keeping all previous. This had the downside of showing all bounding boxes no matter the filters, but also being not performant as the size of the array an number of bounding boxes grew very quickly.
The fix was to clear the array every time new results are fetched. Testing this it seems to have fixed the issue.
To test for yourself, open the map view and view all bounding boxes, then apply a filter that reduces the number of results, view all bounding boxes …
=> Keep bounding boxes in sync with map results

__tests__/routes/web/__snapshots__/accessibility.spec.ts.snap, __tests__/routes/web/__snapshots__/detailsPage.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchPost.spec.ts.snap, __tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, src/services/handlers/searchApi.ts
AGM have now added the `sortBy` querystring param to their API, it would have been nicer if it were in the POST body, like the other filters, but that is not the case and I don't want to waste time going back and forth, so I can accept that for now.
Therefore I have added the querystring to the API fetch query we make e.g. `https://environment-test.data.gov.uk/natural-capital-ecosystem-assessment/search?sortBy=most_relevant`
=> fix(filters): Integrate the sort by UI widget

__tests__/routes/web/__snapshots__/detailsPage.spec.ts.snap, __tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, src/interfaces/queryBuilder.interface.ts, src/utils/queryBuilder.ts, src/utils/searchFilters.ts
The API intends to switch the values used for the `ServiceType` from the IDs it was using to the actual name, much like what happened with the `Oganisation` filters. The API doesn't seem to respond to this filter, with IDs or the actual name, but when it does, this should just work.
=> fix(filters): Update the values to send to the API

__tests__/routes/web/__snapshots__/404.spec.ts.snap, __tests__/routes/web/__snapshots__/accessibility.spec.ts.snap, __tests__/routes/web/__snapshots__/dateSearch.spec.ts.snap, __tests__/routes/web/__snapshots__/detailsPage.spec.ts.snap, __tests__/routes/web/__snapshots__/feeds.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchGet.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchPost.spec.ts.snap, __tests__/routes/web/__snapshots__/home.spec.ts.snap, __tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, __tests__/utils/getGeographyTabData.spec.ts, __tests__/utils/validate.spec.ts, src/utils/getGeographyTabData.ts, src/utils/validate.ts
This will fix the issue, when we view the Geography Details section under more info for Non Spatial search results
- [Search Result More Info](http://localhost:3000/natural-capital-ecosystem-assessment/search/c0395a9b-7705-41a7-912d-b77153b63dde?dt=non-spatial&date-before=&date-after=&licence=&keywords=&scope=all&q=disease&rpp=20&srt=most_relevant&jry=qs&pg=1#geography)
=> Fixing Geography Details section for Non Spatial search results

public/scripts/location.js, src/controllers/web/SearchResultsController.ts, src/utils/constants.ts, src/views/screens/results/template.njk
In this PR, I have fixed the issue related to search results API calling be run run twice. Now on search page load, i will fetch the results from the search result API call.
- [NCEA-266 - Search results seem to be run twice](https://dsp-support.atlassian.net/browse/NCEA-266)
- [NCEA-269 - NCEA-269 Typo on Detail page > Geography tab > Vertical extent](https://dsp-support.atlassian.net/browse/NCEA-269)
- [Search Results](http://localhost:3000/natural-capital-ecosystem-assessment/search?q=disease&jry=qs&pg=1&rpp=20&srt=most_relevant)
=> NCEA-266 Search results seem to be run twice + NCEA-269 Typo on Detail page > Geography tab > Vertical extent

__tests__/utils/getNaturalCapitalTab.spec.ts, src/utils/formatSearchResponse.ts, src/utils/getNaturalCapitalTab.ts
In this PR, I have added the transform function which will convert into the expected classifier table output to generate the table for Theme, Category and Sub Category
- [NCEA-270 - Replace mocks for Natural capital](https://dsp-support.atlassian.net/browse/NCEA-270)
With natural capital theme data
With Empty array of response for Natural Classifiers
- [More Info Natual Tab](http://localhost:4000/natural-capital-ecosystem-assessment/search/ee218908-f1d4-4c30-a325-f49e42809a88?jry=gs&level=1&parent%5B%5D=lvl1_001&cnt=2&pg=1&rpp=20&srt=most_relevant#natural)
=> NCEA-270 Replace mocks for Natural capital

public/scripts/location.js
In this PR, I have limit maximum zoom level on map
- [NCEA-259 - Limit maximum zoom level on map](https://dsp-support.atlassian.net/browse/NCEA-259)
Viewing without map search
Viewing with map search
Viewing all search results
- [Search Results](http://localhost:4000/natural-capital-ecosystem-assessment/search?org=Department+for+Environment%2C+Food+%26+Rural+Affairs&date-before=&date-after=&licence=&keywords=&scope=all&q=fisheries&rpp=20&srt=most_relevant&jry=qs&pg=1)
=> NCEA-259 Limit maximum zoom level on map

src/utils/getFeedsData.ts
We experienced a problem fetching blogs on our local DEV VMs, where the requests consistently failed. However we did not experience this when the app is deployed in the `test` environment.
After some googling it seems it is NodeJS preferring `IPv6` over `IPv4`. This still doesn't explain why it works in `test` though, however having configured the **RSS Parser** to use `IPv4` only, I am getting blogs again on my local setup.
Ticket: https://dsp-support.atlassian.net/browse/NCEA-276
=> fix(blogs): Ensure blog fetching uses IPv4

src/interfaces/searchResponse.interface.ts, src/utils/getNaturalCapitalTab.ts
In this PR, I have fix the issue to display Theme and Category, if there is no Sub-Category. It will also display theme, if there is no category and subcategory
- [NCEA-280 - Single Record view - UI to lookup human readable names for themes,categories and sub-categories](https://dsp-support.atlassian.net/browse/NCEA-280)
=> NCEA-280 Single Record view - UI to lookup human readable names for themes, categories and sub-categories

__tests__/routes/web/__snapshots__/404.spec.ts.snap, __tests__/routes/web/__snapshots__/accessibility.spec.ts.snap, __tests__/routes/web/__snapshots__/dateSearch.spec.ts.snap, __tests__/routes/web/__snapshots__/detailsPage.spec.ts.snap, __tests__/routes/web/__snapshots__/feeds.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchGet.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchPost.spec.ts.snap, __tests__/routes/web/__snapshots__/home.spec.ts.snap, __tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, src/interfaces/searchResponse.interface.ts, src/services/handlers/mocks/more-info-response.ts, src/utils/constants.ts, src/utils/formatSearchResponse.ts, src/utils/getQualityTabData.ts, src/views/partials/results/summary.njk
In this PR, I have added the Dataset reference date in Search Result Section. 
- [NCEA-191 - Update Date Search Filter to use new API params](https://dsp-support.atlassian.net/browse/NCEA-191)
- [Search Results](http://localhost:4000/natural-capital-ecosystem-assessment/search?date-before=&date-after=&licence=&keywords=Water&scope=all&q=disease&rpp=20&srt=most_relevant&jry=qs&pg=1)
- [More Info(http://localhost:4000/natural-capital-ecosystem-assessment/search/bbcb8fca-2c40-441b-96c9-78c36893a4f0?date-before=&date-after=&licence=&keywords=Water&scope=all&q=disease&rpp=20&srt=most_relevant&jry=qs&pg=1#quality)
- ...
=> NCEA-191 Added the Dataset reference date in Search Result Section

__tests__/utils/getAccessTabData.spec.ts, src/interfaces/searchResponse.interface.ts, src/utils/constants.ts, src/utils/getAccessTabData.ts, src/utils/searchFilters.ts
In this PR, I have updated the service type filter for HTTP file download.
- [NCEA-290 - Update filter options for Service Types](https://dsp-support.atlassian.net/browse/NCEA-290)
- [Search Result Page](http://localhost:4000/natural-capital-ecosystem-assessment/search?svt=HTTP+file+download&date-before=&date-after=&licence=&keywords=&scope=all&q=disease&rpp=20&srt=most_relevant&jry=qs&pg=1)
=> NCEA-290 Update filter options for Service Types

__tests__/config/environmentConfig.spec.ts, __tests__/infrastructure/server.spec.ts, __tests__/routes/web/__snapshots__/accessibility.spec.ts.snap, __tests__/routes/web/__snapshots__/dateSearch.spec.ts.snap, __tests__/routes/web/__snapshots__/detailsPage.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchPost.spec.ts.snap, __tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, __tests__/schema/environmentConfig.schema.spec.ts, __tests__/services/handlers/searchApi.spec.ts, __tests__/utils/queryStringHelper.spec.ts, src/config/environmentConfig.ts, src/controllers/web/ClassifierSearchController.ts, src/controllers/web/DateSearchController.ts, src/controllers/web/HomeController.ts, src/interfaces/environmentConfig.interface.ts, src/schema/environmentConfig.schema.ts, src/services/handlers/searchApi.ts, src/utils/queryStringHelper.ts
Replaced the search results count API with the category result count API. The previous API fetched all search result data along with the count, which led to slower performance. The result count API fetches only  the count, significantly improving load time.
- [NCEA-295 - Hook up UI category search to new endpoint](https://dsp-support.atlassian.net/browse/NCEA-294)
Please add the variable into the .env file
`CATEGORY_RESULT_COUNT_API=https://environment-test.data.gov.uk/api/categoryrecordcount`
- Category Pages/link 1](http://localhost:4000/natural-capital-ecosystem-assessment/classifier-search?jry=gs&level=2&parent%5B%5D=lvl1_001&parent%5B%5D=lvl1_002)
=> NCEA-295 - Hook up UI category search to new endpoint

public/scripts/filters.js
In this PR, I have updated the appendMetaSearchParams method to automatically extract and apply filter parameters from URL query parameters. This eliminates the need to explicitly pass additional filter parameters, simplifying the function usage and reducing redundancy.
- [NCEA-275 - Category search data scope error](https://dsp-support.atlassian.net/browse/NCEA-275)
=> NCEA-275 Category search data scope error

public/scripts/filters.js, src/utils/constants.ts, src/utils/queryStringHelper.ts, src/utils/searchFilters.ts
Previously, clearing filters in the search results page would reset the entire URL, removing all query parameters and reloading the page. This behavior disrupted use cases like category-based searches, where level and parents parameters need to persist. This update refines the filter-clearing logic to only remove the applied filter values while retaining existing query parameters such as level and parents. This ensures a smoother user experience and maintains the context of the current search.
- [NCEA-296 -Clear Filters`button removes query information after a classifier search](https://dsp-support.atlassian.net/browse/NCEA-296)
- [Search Result Page](http://localhost:4000/natural-capital-ecosystem-assessment/search?date-before=&date-after=&licence=&keywords=&scope=all …
=> NCEA-296 - Clear Filters button removes query information after a classifier search

public/scripts/keywordsFilter.js, public/scripts/location.js
Previously, switching the scope from `scope=all` to `scope=ncea` triggered a DOM refresh to update map results, but the client-side code handling keywords functionality was lost during this refresh. This commit reintroduces the keywords functionality logic so that it persists and works correctly after the scope change.
- [NCEA-297 - Keywords list does not show up in map view after changing data scope](https://dsp-support.atlassian.net/browse/NCEA-297)
=> NCEA-297 - Keywords list does not show up in map view after changing data scope

public/scripts/categorySearch.js, src/services/handlers/classifierApi.ts, src/utils/constants.ts, src/views/screens/guided_search/classifier_selection.njk
Handled UI and submission behavior for "Monetary" and "Non-monetary" categories when no subcategories are returned from the API. It displays the message: "This category has no subcategories, so all its records will be selected." for Monetary and Non-monetary under the subcategory section .The IDs (lvl2_009 for Monetary and lvl2_010 for Non-monetary) are included as hidden inputs in the form, so they are passed in the search results API call.
- [NCEA 301 - Monetary and non-monetary categories and their parent theme to be shown on subcategory page](https://dsp-support.atlassian.net/browse/NCEA-301)
If user selects non-monetary categories
If user selects Monetary category
If user selects Monetary and non-monetary categories
- [Category …
=> NCEA 301 Monetary and non-monetary categories and their parent theme to be shown on subcategory page

src/utils/getAccessTabData.ts
Removed the null check for the type property in the resources array. If a resource has a null type, it will now default to displaying the "Data Services and Download Area of Interest" table.
- [NCEA-306 - Link to access resources missing for some records](https://dsp-support.atlassian.net/browse/NCEA-306)
=> NCEA-306 Link to access resources missing for some records

src/views/macros/header.njk
Removed the icons from the header links home ,about and news feed
- [NCEA 309 - Remove icons from standard header links](https://dsp-support.atlassian.net/browse/NCEA-309)
- [Home Page](http://localhost:4000/natural-capital-ecosystem-assessment)
=> NCEA 309 Remove icons from standard header links

src/controllers/web/AboutController.ts, src/utils/constants.ts
Changed blog category from NCEA to Natural Capital in the Natural England Blogs API. Updated the About Us page to display the most recent Natural Capital blog posts
- [NCEA-308 - Natural England blog not updating](https://dsp-support.atlassian.net/browse/NCEA-308)
- [Feeds Page](http://localhost:4000/natural-capital-ecosystem-assessment/newsfeed)
- [About Page](http://localhost:4000/natural-capital-ecosystem-assessment/about)
=> NCEA-308 - Natural England blog not updating

__tests__/routes/web/resultsBlock.spec.ts, src/utils/getGeneralTabData.ts, src/views/partials/results/summary.njk
In more Info page, If Study period start date is present, show the start date. If only the end date is present, show the end date in 
- [NCEA-317  - Study period - temporal extent not displayed correctly or consistently](https://dsp-support.atlassian.net/browse/NCEA-317)
- [More Info(http://localhost:4000/natural-capital-ecosystem-assessment/search/3c72669a-1331-4930-a12d-b4f8032aa5cd?q=england+peat+map&jry=qs&pg=1&rpp=20&srt=most_relevant#general)
=> NCEA-317 Study period - temporal extent not displayed correctly or consistently

src/assets/sass/templates/_details.scss
Fixed unwanted scrollbar in Full Downloads and supporting Documentation section. Added min-width and enabled word wrapping for long text
- [NCEA-324 - NCEA-324 'Full downloads and supporting documentation' table requires scrolling to view download link](https://dsp-support.atlassian.net/browse/NCEA-324)
=> NCEA-324 'Full downloads and supporting documentation' table requires scrolling to view download link

src/assets/sass/templates/_results.scss
Resolved the visual glitch in the NCEA contribution section where an unintended gap caused an "AND cut" by removing the spacing between the NCEA image and the contribution text
- [NCEA-341 - Fix spacing issue between NCEA image and contribution text](https://dsp-support.atlassian.net/browse/NCEA-341)
- [Search Result Page](http://localhost:4000/natural-capital-ecosystem-assessment/search?q=ncea&jry=qs&pg=1&rpp=20&srt=most_relevant)
=> NCEA-341 Fix spacing issue between NCEA image and contribution text

__tests__/utils/getAccessTabData.spec.ts, src/utils/getAccessTabData.ts
Show "N/A" in the action col if serviceType is WFS. Show "Preview" with 'explore/{recordId}' if serviceType is WMS.
For the resources with `download=true` in the url, set label to "Download by area of interest and format" and set "Copy Link" action to "NA"
- [NCEA-358 - Update action column rendering for WFS/WMS servicesTypes](https://dsp-support.atlassian.net/browse/NCEA-358)
**NCEA**
**Live DSP**
Set SEARCH_API=https://environment.data.gov.uk/api/search in env variables file
- [More Info](http://localhost:4000/natural-capital-ecosystem-assessment/search/9c41b3c6-2453-44f6-9900-e7821f1a1072?q=National+trees+outside+woodland+map&jry=qs&pg=1&rpp=20&srt=most_relevant#access)
=> NCEA-358 - Update action column rendering for WFS/WMS servicesTypes
