DSP3-apps/ncea-frontend

public/css/application.css, public/scripts/filters.js, src/services/handlers/mocks/classifier-themes-level-2.ts, src/services/handlers/mocks/classifier-themes-level-3.ts, src/utils/formatSearchResponse.ts, src/utils/processFilterRSortOptions.ts
There were a few minor issues in the new filters that needed to be fixed before deploying. They are now fixed and can be verified by testing.
=> Fix minor issues in new filters

public/scripts/filters.js, public/scripts/keywordsFilter.js
In this PR, I have fixed the keyword input issue and applied filters based upon selection
- [NCEA-176 - Fix keyword input](https://dsp-support.atlassian.net/browse/NCEA-176)
- http://localhost:3000/natural-capital-ecosystem-assessment/search?scope=all&date-before=&date-after=&licence=&keywords=Another+free+word+test&q=test&rpp=20&srt=most_relevant&jry=qs&pg=1
=> NCEA-176 - Fix keyword input

__tests__/controllers/web/SearchResultsController.spec.ts, __tests__/routes/web/__snapshots__/404.spec.ts.snap, __tests__/routes/web/__snapshots__/accessibility.spec.ts.snap, __tests__/routes/web/__snapshots__/dateSearch.spec.ts.snap, __tests__/routes/web/__snapshots__/detailsPage.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchGet.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchPost.spec.ts.snap, __tests__/routes/web/__snapshots__/home.spec.ts.snap, __tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, __tests__/services/handlers/searchApi.spec.ts
- I have removed the some skipped testcases because it are using the mock response, So this cases are related to api failure error handle, So we can not test this with mock data.
- replaces the correct expected response data to one of the test case.
Issued Id: NCEA-177.
- ...
=> feat(frontend): Tidy up testcase which are skipped.

__tests__/routes/web/__snapshots__/accessibility.spec.ts.snap, __tests__/routes/web/__snapshots__/detailsPage.spec.ts.snap, __tests__/routes/web/__snapshots__/feeds.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchPost.spec.ts.snap, __tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, src/interfaces/queryBuilder.interface.ts, src/utils/queryBuilder.ts
- I have updated the TemporalExtent key with DateRange in  filters request object.
- also updated the object of the TemporalExtent with new keys, and formatted the values with by appending the day and month to the year by using the data-fns.
Issued Id: NCEA-191.
- ...
=> feat(frontend): Update Date Search Filter to use new API params.

__tests__/routes/web/__snapshots__/accessibility.spec.ts.snap, __tests__/routes/web/__snapshots__/detailsPage.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchPost.spec.ts.snap, __tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, src/utils/searchFilters.ts
- I have updated the acronyms of the organization with there full name.
Issued Id: NCEA-209.
- ...
=> feat(frontend): Change organization filter to use full names.

__tests__/routes/web/__snapshots__/404.spec.ts.snap, __tests__/routes/web/__snapshots__/accessibility.spec.ts.snap, __tests__/routes/web/__snapshots__/dateSearch.spec.ts.snap, __tests__/routes/web/__snapshots__/detailsPage.spec.ts.snap, __tests__/routes/web/__snapshots__/feeds.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchGet.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchPost.spec.ts.snap, __tests__/routes/web/__snapshots__/home.spec.ts.snap, __tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, src/views/partials/results/badges.njk, src/views/partials/results/filters.njk
- I have renames the dspFilterOptions.license to dspFilterOptions.licence, Its a typo error and fixed it.
Issued Id: NCEA-210.
- ...
=> feat(frontend): Licence badge does not display.

__tests__/routes/web/__snapshots__/404.spec.ts.snap, __tests__/routes/web/__snapshots__/accessibility.spec.ts.snap, __tests__/routes/web/__snapshots__/dateSearch.spec.ts.snap, __tests__/routes/web/__snapshots__/detailsPage.spec.ts.snap, __tests__/routes/web/__snapshots__/feeds.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchGet.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchPost.spec.ts.snap, __tests__/routes/web/__snapshots__/home.spec.ts.snap, __tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, src/interfaces/searchResponse.interface.ts, src/utils/formatSearchResponse.ts
- I have debugged the issue, there is api response is changes, hence ui not showing the results.
- I have removed the 'ISearchFields' from the 'ISearchResult', and moved all properties of 'ISearchFields' to  'ISearchResult' then problem is fixed.
- According to interface changes, removed the 'searchFields' in 'transformSearchResponse' function.
Issued Id: NCEA-217.
- ...
=> feat(frontend): Search Results not getting.

__tests__/infrastructure/plugins/views.spec.ts, __tests__/routes/web/__snapshots__/404.spec.ts.snap, __tests__/routes/web/__snapshots__/accessibility.spec.ts.snap, __tests__/routes/web/__snapshots__/dateSearch.spec.ts.snap, __tests__/routes/web/__snapshots__/detailsPage.spec.ts.snap, __tests__/routes/web/__snapshots__/feeds.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchGet.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchPost.spec.ts.snap, __tests__/routes/web/__snapshots__/home.spec.ts.snap, __tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, public/scripts/customScripts.js, src/assets/sass/settings/_colors.scss, src/assets/sass/templates/_about.scss, src/assets/sass/templates/_header.scss, src/assets/sass/templates/_results.scss, src/infrastructure/plugins/views.ts, src/utils/constants.ts, src/views/layout/default.njk, src/views/screens/feeds/template.njk, src/views/screens/home/accessibility.njk, src/views/screens/home/help.njk, src/views/screens/home/privacy_policy.njk, src/views/screens/home/template.njk, src/views/screens/home/terms_conditions.njk
- I have add the /about and /feeds navigation links to the header.
- I used the gov-uk design system of 'service-navigation' component, which will take the array of objects of link details as {text: '/about', href: 'link'}.
- I defined the all the nav links in the constants.ts file, we can add and remove the links at single place here.
- I have added the javascript function on document load, which will handle the link active indication on client side.
Issued Id: NCEA-213.
- …
=> feat(frontend): Add navigation to header.

__tests__/routes/web/__snapshots__/accessibility.spec.ts.snap, __tests__/routes/web/__snapshots__/detailsPage.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchPost.spec.ts.snap, __tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, src/interfaces/searchResponse.interface.ts, src/utils/formatSearchResponse.ts
This branch, will add the  organisation value to search results and more info section
- [NCEA-222 - Search Results Filters not working](https://dsp-support.atlassian.net/browse/NCEA-222)
- [Search Results](http://localhost:3000/natural-capital-ecosystem-assessment/search?q=disease&jry=qs&pg=1&rpp=20&srt=most_relevant)
=> NCEA-222 feat(frontend): added the organisation value to search results and more info section

src/infrastructure/plugins/views.ts
In this, remove the login url check for local development server
=> NCEA - 41 User login and logout

__tests__/routes/web/__snapshots__/404.spec.ts.snap, __tests__/routes/web/__snapshots__/accessibility.spec.ts.snap, __tests__/routes/web/__snapshots__/dateSearch.spec.ts.snap, __tests__/routes/web/__snapshots__/detailsPage.spec.ts.snap, __tests__/routes/web/__snapshots__/feeds.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchGet.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchPost.spec.ts.snap, __tests__/routes/web/__snapshots__/home.spec.ts.snap, __tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, public/scripts/filters.js, public/scripts/location.js, src/utils/queryStringHelper.ts
- Fixed the issue by adding "addAllCheckboxListeners" function in the "getMapFilters".
Issued Id: DCI-224.
- ...
=> fix(filters): Map results of filters check boxes are not working as expected

public/scripts/location.js
This PR will fix the map result count issue
- [NCEA-240 - Spatial search results count](https://dsp-support.atlassian.net/browse/NCEA-240)
- [Search Results](http://localhost:3000/natural-capital-ecosystem-assessment/search?dt=non-spatial&date-before=&date-after=&licence=&keywords=&scope=all&q=disease+investigations&rpp=20&srt=most_relevant&jry=qs&pg=1)
=> NCEA-240 Spatial search results count

__tests__/routes/web/__snapshots__/404.spec.ts.snap, __tests__/routes/web/__snapshots__/accessibility.spec.ts.snap, __tests__/routes/web/__snapshots__/dateSearch.spec.ts.snap, __tests__/routes/web/__snapshots__/detailsPage.spec.ts.snap, __tests__/routes/web/__snapshots__/feeds.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchGet.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchPost.spec.ts.snap, __tests__/routes/web/__snapshots__/home.spec.ts.snap, __tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, src/assets/sass/templates/_results.scss, src/views/partials/results/badges.njk
I have fixed the typo on Licence filter name.
Added the animation on the drop down arrow.
Issued Id: NCEA-[244](https://dsp-support.atlassian.net/browse/NCEA-244?atlOrigin=eyJpIjoiMmIyMDcxNjA0NDgzNGFlNGJiMzBjMDRjZmFhYzIwYTMiLCJwIjoiaiJ9), [248](https://dsp-support.atlassian.net/browse/NCEA-248?atlOrigin=eyJpIjoiMWY3NWUwMjIzMWNiNDBjOGFkOWM1MDJjMTEyZTMwNzEiLCJwIjoiaiJ9).
- ...
=> fix(filters): Filter drop down not animating on selection and Typo on Licence filter in UI

__tests__/utils/formatSearchResponse.spec.ts, __tests__/utils/getNaturalCapitalTab.spec.ts, src/interfaces/searchResponse.interface.ts, src/utils/constants.ts, src/utils/getNaturalCapitalTab.ts
In this PR, it will add the mock data for Natural Capital data based upon the mock data provided.
- [NCEA-239 - Wrong information 'Natural Capital' tab of dataset detail page](https://dsp-support.atlassian.net/browse/NCEA-239)
- [More Info Search Result](http://localhost:3000/natural-capital-ecosystem-assessment/search/fae1c657-64bb-414c-a1e9-e992b2e7ec03?q=disease&jry=qs&pg=1&rpp=20&srt=most_relevant#natural)
=> NCEA-239 Wrong information 'Natural Capital' tab of dataset detail page

public/scripts/location.js
This PR will fix the Change of scope in map view issue when there is no record exist
- [NCEA-258 - Change of scope in map view](https://dsp-support.atlassian.net/browse/NCEA-258)
- [Search Result Map View](http://localhost:3000/natural-capital-ecosystem-assessment/search?org=Environment+Agency&date-before=&date-after=&licence=&keywords=&scope=all&q=fisheries&rpp=20&srt=most_relevant&jry=qs&pg=1)
=> NCEA 258 - Change of scope in map view

__tests__/routes/web/__snapshots__/404.spec.ts.snap, __tests__/routes/web/__snapshots__/accessibility.spec.ts.snap, __tests__/routes/web/__snapshots__/dateSearch.spec.ts.snap, __tests__/routes/web/__snapshots__/detailsPage.spec.ts.snap, __tests__/routes/web/__snapshots__/feeds.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchGet.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchPost.spec.ts.snap, __tests__/routes/web/__snapshots__/home.spec.ts.snap, __tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, src/assets/sass/_root.scss, src/assets/sass/templates/_footer.scss, src/views/layout/default.njk
feat(Footer update): Update the footer section same as DSP Apps
I have updated the footer section styles as per the new footer design of DSP apps.
Issued Id: NCEA-[263](https://dsp-support.atlassian.net/browse/NCEA-263?atlOrigin=eyJpIjoiMzY0ODg2NGViMjYxNDkxNWI2YzI3MDY0ZTdmZWRhZGMiLCJwIjoiaiJ9).
- ...
=> Ncea 263 footer update

__tests__/routes/web/__snapshots__/accessibility.spec.ts.snap, __tests__/routes/web/__snapshots__/detailsPage.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchPost.spec.ts.snap, __tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, src/views/screens/guided_search/classifier_selection.njk
- I have fixed issue, issue is missing the hidden default page number form element in the form, So the form action is ignoring it.
Issued Id: NCEA-[273](https://dsp-support.atlassian.net/browse/NCEA-273?atlOrigin=eyJpIjoiOWQzOTE1ZWY3YzVlNDRjZGJhNWU5ZDg2ODAxZDAwNGEiLCJwIjoiaiJ9).
- ...
=> fix(pagination): Page number getting NaN

src/utils/constants.ts
Updated the Join out mailing list link in about us page
- [NCEA 287 - Update quick link to 'Join our mailing list'](https://dsp-support.atlassian.net/browse/NCEA-287)
=> NCEA 287 Update quick link to 'Join our mailing list'

src/views/layout/default.njk
Updated the Google Analytics ID
Update the **GTM_ID** in .env file to G-12JL3WT6ZY
- [NCEA-299 - Change Google Analytics ID to the main DSP one](https://dsp-support.atlassian.net/browse/NCEA-299)
=> NCEA-299 Change Google Analytics ID to the main DSP one

public/images/email-icon-new.svg, public/images/mailing-list.svg, src/assets/sass/templates/_about.scss, src/utils/constants.ts, src/views/screens/about/template.njk
Updated quick links svg icons in about us page. Added the brochure pdf link
- [NCEA-300 - Updates to content on Home and About Page](https://dsp-support.atlassian.net/browse/NCEA-300)
=> NCEA-300 Updates to content on Home and About Page

src/assets/sass/templates/_about.scss, src/utils/constants.ts, src/views/screens/about/template.njk, src/views/screens/guided_search/classifier_selection.njk, src/views/screens/home/template.njk
Renamed "Category Search" to "Natural Capital Search". Updated related links on the About Us page based on feedback. Added spacing between partner logos
- [NCEA-314 - Rename Category Search to Natural Capital Search](https://dsp-support.atlassian.net/browse/NCEA-314)
=> NCEA-314 Rename Category Search to Natural Capital Search

__tests__/infrastructure/plugins/views.spec.ts, __tests__/routes/web/__snapshots__/404.spec.ts.snap, __tests__/routes/web/__snapshots__/accessibility.spec.ts.snap, __tests__/routes/web/__snapshots__/dateSearch.spec.ts.snap, __tests__/routes/web/__snapshots__/detailsPage.spec.ts.snap, __tests__/routes/web/__snapshots__/feeds.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchGet.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchPost.spec.ts.snap, __tests__/routes/web/__snapshots__/home.spec.ts.snap, __tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, __tests__/utils/getAccessTabData.spec.ts, public/scripts/moreInfo.js, src/infrastructure/plugins/views.ts, src/interfaces/searchResponse.interface.ts, src/utils/getAccessTabData.ts, src/views/layout/default.njk
Implemented a function to fetch the resource URL and check the response status. If the response is 200, trigger the file download under the Full downloads and supporting documentation section. If the resource is not OK eg, 401 or 404, will redirect to the DSP application
- [NCEA-35 - Access data hosted on DSP from within NCEA portal](https://dsp-support.atlassian.net/browse/NCEA-35)
- [Moreinfo page](http://localhost:3000/natural-capital-ecosystem-assessment/search/94a0d2cf-4c1d-4c82-b5fc-c621b07074a3?q=semi+natural+woodland&jry=qs&pg=1&rpp=20&srt=most_relevant#access)
=> NCEA-35 Access data hosted on DSP from within NCEA portal

src/utils/constants.ts
Replace the old url from the "Learn more about NCEA" button on about us page with the updated new link.
- [NCEA-356 -  Update slide pack link on About Page](https://dsp-support.atlassian.net/browse/NCEA-356)
=> NCEA-356: Update slide pack link on About Page
